// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db_quaries

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	AccountID     uuid.UUID
	Username      string
	Email         string
	Password      string
	EmailVerified bool
	Active        bool
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	DeletedAt     pgtype.Timestamp
}

type Notification struct {
	NotificationID   uuid.UUID
	NotificationType string
	Read             bool
	UserID           uuid.UUID
	CreatedAt        pgtype.Timestamp
	UpdatedAt        pgtype.Timestamp
	DeletedAt        pgtype.Timestamp
}

type Reaction struct {
	ReactionID uuid.UUID
	React      bool
	UserID     uuid.UUID
	ViewID     uuid.UUID
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	DeletedAt  pgtype.Timestamp
}

type RequestInfo struct {
	RequestInfoID uuid.UUID
	UserID        uuid.UUID
	ViewID        uuid.UUID
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	DeletedAt     pgtype.Timestamp
}

type View struct {
	ViewID    uuid.UUID
	Title     string
	Paragraph string
	UserID    uuid.UUID
	Public    bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}
